# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  database: <%= ENV.fetch('MYSQL_DATABASE') %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  database: <%= ENV.fetch('MYSQL_DATABASE') %>