version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app/campusflora
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    env_file:
      - .env/development/database
      - .env/development/web
  mysql:
    image: mysql:5.7
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: